chat/urls.py
# from django.contrib.auth.views import logout
from django.urls import path
from . import views

app_name="chat"
urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    # path('logout/', logout, {'next_page': 'index'}, name='logout'),
    # path('register/', views.register_view, name='register'),

]

diets/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('user/', include('users.urls')),
    path('', include('home.urls')),
    path('im/', include('chat.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name="home"
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('dietologs/', views.dietolog_list, name='dietologs'),
    path('dietologs/<int:dietolog_id>', views.dietolog_profile, name='dietolog_profile'),
    path('calcs/', views.calc_bzhu, name='calc_bzhu'),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
   	path('register/', views.register, name='register'), 
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('activate_profile/', views.activate_profile, name='activate_profile')
]


home/models.py
from django.db import models

home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from users.models import ProfileConsultant, SiteUser
from django.db.models import Prefetch
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'home/index.html', {})


@login_required
def dietolog_list(request):
    # dietologs_profile = SiteUser.objects.prefetch_related(
    #     Prefetch(
    #         "profileconsultant",
    #         queryset=ProfileConsultant.objects.filter(is_activate=True),
    #         to_attr="profileconsultant_activate",
    #     )
    # )
    # dietologs_profile = SiteUser.objects.select_related("profileconsultant").filter(is_activate=True)
    dietologs_profile = ProfileConsultant.objects.filter(is_activate=True)
    context = {'diet_profile':dietologs_profile}
    return render(request, 'home/dietolog_list.html', context)

@login_required
def dietolog_profile(request, dietolog_id):
    dietolog_obj = get_object_or_404(ProfileConsultant, is_activate=True, user_id=dietolog_id)
    return render(request, "users/profile_id.html", {"dietolog": dietolog_obj})


def calc_bzhu(request):
    return render(request, "home/calc_bzhu.html")
def about(request):
    return HttpResponse('<h1>about</h1>')
# Create your views here.

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Обязательные мета-теги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap, иконки и шрифт -->
     <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>   
     <link rel="stylesheet" type="text/css" href="{% static 'home/css/main.css' %}">
     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <!--Import materialize.css-->
     {% comment %} <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
     <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/> {% endcomment %}
     <script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
     <script src="{% static 'home/js/bootstrap.min.js'%}"></script>
     <script src="{% static 'home/js/jquery.validate.min.js' %}"></script>
      <script src="{% static 'home/js/calcs.js' %}"></script>
      {% comment %} <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/chat.js' %}"></script> {% endcomment %}
    
    {% if title %}
        <title> Онлайн диетолог -  {{ title }}</title>
    {% else %}
        <title>Онлайн диетолог</title>
    {% endif %}
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home:index' %}">Онлайн-диетолог</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link {% if request.path == "/" %}active {% endif %}" aria-current="page" href="{% url 'home:index'%}">Главная</a>
              <a class="nav-link {% if request.path == "/dietologs/" %}active {% endif %}" href="{% url 'home:dietologs' %}">Диетологи</a>
              <a class="nav-link {% if request.path == "/calcs/" %}active {% endif %}" href="{% url 'home:calc_bzhu' %}">Калькулятор калорий</a>
    
            </div>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-link {% if request.path == "/user/profile/" %}active {% endif %}" href="{% url 'users:profile'%}">Профиль</a>
                <a class="nav-link" href="{% url 'chat:chats'%}">Диалоги</a>
                <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                {% else %}
                <a class="nav-link" href="{% url 'login' %}">Вход</a>
                <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
              </div>
          </div>
        </div>
    </nav>
</header>
<main class="container">
    <div class="row">
        <div class="col-12 py-4">
            {% if messages %}
        	{% for message in messages %}
          	<div class="alert alert-{{ message.tags }}">
            	{{ message }}
          	</div>
        	{% endfor %}
            {% endif %}
            {% block content %} {% endblock %}
           
        </div>
    </div>
</main>


   
</body>
</html>

home/templates/home/calc_bzhu.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% load static %}
    <div class="content">

        <h2>Расчет суточной нормы калорий и БЖУ </h2>
        <form class="calc4 calc-tools"
              id="calc4"
              method="post"
              action=""
              novalidate="novalidate">
            <div class="form-group">
                <div class="cl3__label">Ваш пол:</div>
                <label class="radio-inline">
                    <input type="radio"
                           name="gender"
                           class="cl4_sex"
                           value="m"
                           checked="checked">
                    <span style="font-size:17px;">Мужской</span>
                </label>
                <label class="radio-inline">
                    <input type="radio" name="gender" class="cl4_sex" value="f">
                    <span style="font-size:17px;">Женский</span>
                </label>
            </div>
            <div class="form-group">
                <label class="cl3__label">Ваш возраст:</label>
                <div class="right-input">
                    <input type="text"
                           name="cl4_voz"
                           id="cl4_voz"
                           class="cl3__input form-control valid">
                    <div class="error-info in-1"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="cl3__label">Ваш рост (см):</div>
                <div class="right-input">
                    <input type="text" name="cl4_rost" id="cl4_rost" class="cl3__input valid">
                    <div class="error-info in-2"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="cl3__label">Ваш вес, кг:</div>
                <div class="right-input">
                    <input type="text" name="cl4_ves" id="cl4_ves" class="cl3__input valid">
                    <div class="error-info in-3"></div>
                </div>
            </div>
            <div class="form-group">
                <div class="cl3__label">Ваш образ жизни:</div>
                <div class="right-input">
                    <select name="life" id="cl4_ob" class="form-control valid">
                        <option value="">Не знаю</option>
                        <option value="1.2">Сидячий, малоподвижный</option>
                        <option value="1.375">Легкая активность (упражнения 1-3 раза в неделю)</option>
                        <option value="1.55">Средняя активность (тренировки 3-5 раз в неделю)</option>
                        <option value="1.725">Высокая активность (высокие нагрузки каждый день)</option>
                        <option value="1.9">Экстремально высокая активность</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="cl3__label">Ваша цель:</div>
                <div class="right-area">
                    <div class="radio">
                        <label>
                            <input type="radio" name="goal" id="goal" class="cl4_need valid" value="low">
                            <span style="font-size:16px;">Сбросить вес</span>
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio"
                                   name="goal"
                                   id="goal"
                                   class="cl4_need valid"
                                   value="high">
                            <span style="font-size:16px;">Набрать мышечную массу</span>
                        </label>
                    </div>
                    <div class="radio">
                        <label>
                            <input type="radio" name="goal" id="goal" class="cl4_need valid" value="eq">
                            <span style="font-size:16px;">Поддерживать вес</span>
                        </label>
                    </div>
                    <label for="goal" class="error" style="display:none;"></label>
                    <div class="error-info in-4"></div>
                </div>
            </div>
            <div>
                <input type="button" class="cl3_btn" id="cl4_submit" value="Считать">
            </div>
            <div id="cl4_result" style="display:none;">
                <b>Суточная норма калорий:</b>
                <br>
                по среднему расходу на килограмм <span class="cl4_rsrk">2600&nbsp;-&nbsp;3000</span>;
                <br>
                по формуле Харриса-Бенедикта <span class="cl4_rxb">2923</span>;
                <br>
                по формуле Миффлина - Сан Жеора <span class="cl4_rmsj">2410</span>.
                <br>
                <b>Ориентиры для
                    <div class="cl4_result_name" style="display: inline"></div>
                :</b>
                <br>
                диапазон калорий <span class="cl4_rd">2290&nbsp;-&nbsp;2531</span>;
                <br>
                суточная норма белка <span class="cl4_rb">143&nbsp;-&nbsp;221</span> грамм;
                <br>
                суточная норма жиров <span class="cl4_rj">64&nbsp;-&nbsp;84</span> грамм;
                <br>
                суточная норма углеводов <span class="cl4_ru">258&nbsp;-&nbsp;348</span> грамм.
                <br>
            </div>
            <input type="hidden" name="ak_bib" value="">
            <input type="hidden" name="ak_bfs" value="1685281712813">
            <input type="hidden" name="ak_bkpc" value="0">
            <input type="hidden" name="ak_bkp" value="">
            <input type="hidden" name="ak_bmc" value="757;3189,43;105,8415;">
            <input type="hidden" name="ak_bmcc" value="3">
            <input type="hidden" name="ak_bmk" value="">
            <input type="hidden" name="ak_bck" value="">
            <input type="hidden" name="ak_bmmc" value="6">
            <input type="hidden" name="ak_btmc" value="0">
            <input type="hidden" name="ak_bsc" value="11">
            <input type="hidden" name="ak_bte" value="">
            <input type="hidden" name="ak_btec" value="0">
            <input type="hidden"
                   name="ak_bmm"
                   value="585,531;83,302;2602,2871;31,1314;2307,949;3671,263;">
        </form>
    </div>
{% endblock content %}

home/templates/home/dietolog_list.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content">

  {% for duser in diet_profile %}
    <div class="row mb-3">
        <div class="card">

            <div class="card-body">
              <div class="row ">
                <div class="col-2 text-center">
                     <img class="rounded-circle" height="100" src="{{ duser.image.url}}">
                </div>
                <div class="col-10">
              <h5 class="card-title"><a href={% url 'home:dietolog_profile' duser.user_id %}>{{ duser.lastname}} {{ duser.firstname}} {{ duser.surname}}</a></h5>
              <p class="card-text">{{ duser.education}}</p>
              <p class="card-text">Опыт работы: {{ duser.experience}} лет</p>
              <p class="card-text">{{ duser.description}}</p>
              {% comment %} <a href="#" class="btn btn-primary">Go somewhere</a> {% endcomment %}
                </div>
              </div>
            </div>
          </div>
    </div>
    {% endfor %}

    
</div>
{% endblock content %}

home/templates/home/index.html
{% extends "home/base.html" %}
{% block content %}
    {% comment %} {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %} {% endcomment %}

    <div class="services-dashboard innder row">

        <div class="block-item doctors-onduty col-12 col-xl-5">
          <h2>Консультация врача-диетолога</h2>

          <div class="description-text">Опытный  врач свяжется с вами
                  , проведет консультацию, задаст вопросы и даст рекомендации</div>
          <div class="button-wrap">
              <a class="link" href="{% url 'home:dietologs' %}">К списку диетологов</a>
          </div>
      </div>

      <div class="block-item col-12 col-xl-3 calc-help filter">
        <h2>Калькулятор калорий</h2>

        <div class="description-text">
          <p>Рассчитайте важные показатели для эффективного похудения</p>
        </div>

      

        <a href="{% url 'home:calc_bzhu' %}" class="link on-calc-help">
            Рассчитать
        </a>
    </div>
    <div class="block-item col-12 col-xl-3 profile-card filter">
      <h2>Отслеживайте показатели</h2>

      <div class="description-text">
        <p>В личном профиле можно отслеживать показатели и общаться со специалистами</p>
      </div>

    

      <a href="{% url 'users:profile' %}" class="link on-calc-help">
          Перейти
      </a>
  </div>
    </div>
{% endblock content %}