chat/urls.py
# from django.contrib.auth.views import logout
from django.urls import path
from . import views

app_name="chat"
urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    # path('logout/', logout, {'next_page': 'index'}, name='logout'),
    # path('register/', views.register_view, name='register'),

]

diets/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('user/', include('users.urls')),
    path('', include('home.urls')),
    path('im/', include('chat.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name="home"
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('dietologs/', views.dietolog_list, name='dietologs'),
    path('dietologs/<int:dietolog_id>', views.dietolog_profile, name='dietolog_profile'),
    path('calcs/', views.calc_bzhu, name='calc_bzhu'),
]

users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
   	path('register/', views.register, name='register'), 
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('activate_profile/', views.activate_profile, name='activate_profile')
]


chat/models.py
from users.models import SiteUser
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(SiteUser, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(SiteUser, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from users.models import SiteUser as User
from django.forms import TextInput


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields=['username','password1','password2']
        widgets = {
            'username': TextInput(attrs={'class':'form-control'}),
        }

chat/views.py
from django.contrib.auth import authenticate, login
# from django.contrib.auth.models import User
from users.models import SiteUser as User
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from chat.models import Message
from chat.forms import SignUpForm
from chat.serializers import MessageSerializer, UserSerializer


def index(request):
    if request.user.is_authenticated:
        return redirect('chat:chats')
    if request.method == 'GET':
        return render(request, 'chat/index.html', {})
    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            return HttpResponse('{"error": "User does not exist"}')
        return redirect('chat:chats')



@csrf_exempt
def message_list(request, sender=None, receiver=None):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


def register_view(request):
    """
    Render registration template
    """
    if request.method == 'POST':
        print("working1")
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('chat:chats')
    else:
        print("working2")
        form = SignUpForm()
    template = 'chat/register.html'
    context = {'form':form}
    return render(request, template, context)


def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('home:index')
    if request.method == "GET":
        users_receiver = list(Message.objects.filter(sender=request.user.id).distinct().values_list('receiver', flat=True))
        users_sender = list(Message.objects.filter(receiver=request.user.id).distinct().values_list('sender', flat=True))
        users = User.objects.filter(id__in= (users_receiver + users_sender)).exclude(id=request.user.id)
        return render(request, 'chat/chat.html',
                      {'users': users})


def message_view(request, sender, receiver):
    if not request.user.is_authenticated:
        return redirect('home:index')
    if request.method == "GET" and request.user.id == sender:
        users_receiver = list(Message.objects.filter(sender=request.user.id).distinct().values_list('receiver', flat=True))
        users_receiver.append(receiver)
        users_sender = list(Message.objects.filter(receiver=request.user.id).distinct().values_list('sender', flat=True))
        users = User.objects.filter(id__in= (users_receiver + users_sender)).exclude(id=request.user.id)
        return render(request, "chat/messages.html",
                      {'users': users,
                       'receiver': User.objects.get(id=receiver),
                       'messages': Message.objects.filter(sender_id=sender, receiver_id=receiver) |
                                   Message.objects.filter(sender_id=receiver, receiver_id=sender)})
    else:
        return redirect('chat:chats')

chat/templates/chat/chat.html
{% extends "chat/index.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col-3 s2">
        <div class="card">
            <div class="collection">
                {% for user in users %}
                
                {% if user.is_consultant %}
                <a href="{% url 'chat:chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                    <img src="{{user.profileconsultant.image.url}}" class=" rounded-circle account-img col s3" height="50" >
                    <div class="col s8">
                    <span class="title" style="font-weight: bolder">{{user.profileconsultant.lastname }} {{user.profileconsultant.firstname }} {{user.profileconsultant.surname }}</span>
                    </div>
                </a>
                {% else %}
                <a href="{% url 'chat:chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                    <img src="{{user.profileuser.image.url}}" class=" rounded-circle account-img col s3" height="40" width="20">
                    <div class="col s8">
                    <span class="title" style="font-weight: bolder">{{user.profileuser.lastname }} {{user.profileuser.firstname }} {{user.profileuser.surname }}</span>
                    </div>
                </a>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating lighten-2 waves-effect waves-light" style="background-color: gray"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load static %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock content %}

chat/templates/chat/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Обязательные мета-теги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap, иконки и шрифт -->
     <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.min.css' %}">
     <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>   
     <link rel="stylesheet" type="text/css" href="{% static 'home/css/main.css' %}">
     <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <!--Import materialize.css-->
     <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
     <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
     <script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
     <script src="{% static 'home/js/bootstrap.min.js'%}"></script>
     <script src="{% static 'home/js/jquery.validate.min.js' %}"></script>
      <script src="{% static 'home/js/calcs.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    
    {% if title %}
        <title> Онлайн диетолог -  {{ title }}</title>
    {% else %}
        <title>Онлайн диетолог</title>
    {% endif %}
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home:index' %}">Онлайн-диетолог</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link {% if request.path == "/" %}active {% endif %}" aria-current="page" href="{% url 'home:index'%}">Главная</a>
              <a class="nav-link {% if request.path == "/dietologs/" %}active {% endif %}" href="{% url 'home:dietologs' %}">Диетологи</a>
              <a class="nav-link {% if request.path == "/calcs/" %}active {% endif %}" href="{% url 'home:calc_bzhu' %}">Калькулятор калорий</a>
    
            </div>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-link {% if request.path == "/user/profile/" %}active {% endif %}" href="{% url 'users:profile'%}">Профиль</a>
                <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                {% else %}
                <a class="nav-link" href="{% url 'login' %}">Вход</a>
                <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
              </div>
          </div>
        </div>
    </nav>
</header>
<main class="container-fluid">
    <div class="row">
        <div class="col-12 py-2">

            {% block content %} {% endblock %}
           
        </div>
    </div>
</main>


   
</body>
</html>

chat/templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    {% comment %} <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">Вы</div> {% endcomment %}
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    {% comment %} <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div> {% endcomment %}
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

chat/templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    {{ form.username }}
                    <label for="id_username" data-error="Username already taken">Username</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password1 }}
                    <label for="id_password">Password</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password2 }}
                    <label for="id_password2">Repeat Password</label>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                <div class="right">
                    <button class="btn blue waves-effect waves-light pull-s12">Register</button>
                </div>
                </div>
            </div>
    </form>
{% endblock %}