chat/urls.py
# from django.contrib.auth.views import logout
from django.urls import path
from . import views

app_name="chat"
urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    # path('logout/', logout, {'next_page': 'index'}, name='logout'),
    # path('register/', views.register_view, name='register'),

]

diets/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('user/', include('users.urls')),
    path('', include('home.urls')),
    path('im/', include('chat.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
   	path('register/', views.register, name='register'), 
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('activate_profile/', views.activate_profile, name='activate_profile')
]


users/models.py
from django.db import models
from PIL import Image
from django.contrib.auth.models import AbstractUser


# Create your models here.

class SiteUser(AbstractUser):
    is_consultant = models.BooleanField(default=False, verbose_name='Регистрируюсь как диетолог')



class ProfileConsultant(models.Model):
    user = models.OneToOneField(SiteUser, on_delete=models.CASCADE)
    firstname = models.TextField(verbose_name="Имя", max_length=200, null=True)
    lastname = models.TextField(verbose_name="Фамилия", max_length=200, null=True)
    surname = models.TextField(verbose_name="Отчество", max_length=200, null=True)
    education = models.TextField(verbose_name="Образование", max_length=500, null=True)
    experience = models.IntegerField(verbose_name="Опыт", null=True)
    is_activate = models.BooleanField(verbose_name="Профиль активирован", null=True)
    description = models.TextField(verbose_name="Описание", max_length=500, null=True)
    image = models.ImageField(verbose_name="Изображение профиля",  default='default.jpg', upload_to='profile_pics')
    def __str__(self):
        return f'{self.user.username} Profile Consultant'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class ProfileUser(models.Model):
    SEX_CHOICES =(
    ("M", "Мужской"),
    ("F", "Женский"),
    )
    user = models.OneToOneField(SiteUser, on_delete=models.CASCADE)
    firstname = models.TextField(verbose_name="Имя", max_length=200, null=True)
    lastname = models.TextField(verbose_name="Фамилия", max_length=200, null=True)
    surname = models.TextField(verbose_name="Отчество", max_length=200, null=True)
    sex = models.TextField(verbose_name="Пол", max_length=1, null=True, choices=SEX_CHOICES)
    bday = models.DateField(verbose_name="Дата рождения", default='1990-01-01')
    height = models.IntegerField(verbose_name="Рост (см)", default=0)
    weight = models.FloatField(verbose_name="Вес (кг)", default=0)
    image = models.ImageField(verbose_name="Изображение профиля",  default='default.jpg', upload_to='profile_pics')
    def __str__(self):
        return f'{self.user.username} Profile User'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import SiteUser
from .models import ProfileConsultant
from .models import ProfileUser
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = SiteUser
        fields = ['username', 'email', 'password1', 'password2', 'is_consultant']

class ConsultantProfileForm(forms.ModelForm):
    firstname = forms.CharField(label="Имя")
    lastname = forms.CharField(label="Фамилия")
    surname = forms.CharField(label="Отчество")

    class Meta:
        model = ProfileConsultant
        fields = ['firstname','lastname','surname','education','experience','description', 'image']

class UserProfileForm(forms.ModelForm):
    firstname = forms.CharField(label="Имя")
    lastname = forms.CharField(label="Фамилия")
    surname = forms.CharField(label="Отчество")
    # iterable
    
   
    class Meta:
        model = ProfileUser
        fields = ['firstname','lastname','surname','sex', 'bday','height','weight', 'image']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm
from .forms import ConsultantProfileForm
from .models import ProfileConsultant
from . import utils
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Ваш аккаунт создан: можно войти на сайт.')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profile(request):
    profile_or_none = utils.get_profile_or_none(request)
    if profile_or_none is None:
        messages.error(request, 'Для начала работы создайте профиль')
        return redirect('users:edit_profile') 
    else:
        context = utils.get_profile_context(request)
        template = utils.get_template_profile(request)
        return render(request, template, context)

@login_required
def edit_profile(request):
    UserForm = utils.get_profile_forms(request)
    if request.method =="POST":
        profile = utils.get_profile_user(request)
        profile_form = UserForm(request.POST,request.FILES, instance=profile)  
        if profile_form.is_valid():
            check = profile_form.save()
            # check.user = request.user
            # check.save()
            messages.success(request, 'Ваш профиль успешно обновлен.')
            return redirect('users:profile') 
    profile_or_none = utils.get_profile_or_none(request)
    if profile_or_none:
        form = UserForm(instance=profile_or_none)
    else:
        form = UserForm()
    return render(request, 'users/edit_profile.html', {'form':form})

@login_required
def activate_profile(request):
    if hasattr(request.user,'profileconsultant'):
        profile_object = request.user.profileconsultant
        profile_object.is_activate = not profile_object.is_activate
        profile_object.save()
    return redirect('users:profile')  

users/templates/users/edit_profile.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class"text-danger warning_message">{{ text_message }}</div>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Сохранить</button>
        </div>
    </form>
    </div>
{% endblock content %}

users/templates/users/login.html

{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Вход</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Войти</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Нужен аккаунт? <a class="ml-2" href="{% url 'users:register' %}">Регистрация</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "home/base.html" %}
{% block content %}
    <h2>Вы вышли из своей учетной записи</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Войти</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
       
      <div class="account-heading row text-center">
        <div class="col-12">
          <img class="rounded-circle mx-auto account-img align-self-center" height="100" src="{{ user.profileconsultant.image.url }}">
          <p><span class="badge bg-info">Специалист</span></p>
          <h2 class="">{{ user.profileconsultant.lastname }}  
            {{ user.profileconsultant.firstname }} {{user.profileconsultant.surname}}
            </h2>
            
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <div class=" account-description row">
        <div class="col-12">
          <p class="text-secondary"> Образование</p>
          <p>{{ user.profileconsultant.education}} </p>
          <p class="text-secondary"> Опыт работы</p>
          <p>{{ user.profileconsultant.experience}} </p>
          <p class="text-secondary"> Описание</p>
          <p>{{ user.profileconsultant.description}} </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-6 text-start">
        {% if user.profileconsultant.is_activate%}
        <span class="text-success">Ваш профиль активирован</span>
        <a class="btn btn btn-outline-secondary" href="{% url 'users:activate_profile' %}" role="button">Деативировать</a>
        {%else%}
        <span class="text-error">Ваш профиль не активирован (не выводится в списке диетологов) </span>
        <a class="btn btn btn-outline-success" href="{% url 'users:activate_profile' %}" role="button">Активировать</a>
        {% endif %}
      </div>
      <div class="col-6 text-end">
        <a class="btn btn-outline-primary" href="{% url 'users:edit_profile' %}" role="button">Редактировать профиль</a>
      </div>
    </div>
{% endblock content %}

users/templates/users/profile_id.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
       
      <div class="account-heading row text-center">
        <div class="col-12">
          <img class="rounded-circle mx-auto account-img align-self-center" height="100" src="{{ dietolog.image.url }}">
          <p><span class="badge bg-info">Специалист</span></p>
          <a class="btn btn-outline-primary"
           href="{% url 'chat:chat' request.user.id dietolog.user.id %}"
           role="button">Диалог</a>
          <h2 class="">{{ dietolog.lastname }}  
            {{ dietolog.firstname }} {{ dietolog.surname }}
            </h2>
            
          
        </div>
      </div>
      <div class=" account-description row">
        <div class="col-12">
          <p class="text-secondary"> Образование</p>
          <p>{{ dietolog.education }} </p>
          <p class="text-secondary"> Опыт работы</p>
          <p>{{ dietolog.experience }} лет</p>
          <p class="text-secondary"> Описание</p>
          <p>{{ dietolog.description }} </p>
        </div>
      </div>
    </div>
{% endblock content %}

users/templates/users/profile_user.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <div class="account-heading row text-center">
      <div class="col-12">
        <img class="rounded-circle mx-auto account-img align-self-center"
             height="100"
             src="{{ user.profileuser.image.url }}">
        <h2 class="">
          {{ user.profileuser.lastname }}
          {{ user.profileuser.firstname }} {{ user.profileuser.surname }}
        </h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>
    <div class="row">
      <div class="col-12 text-center">
        <a class="btn btn-outline-primary"
           href="{% url 'users:edit_profile' %}"
           role="button">Редактировать профиль</a>
      </div>
    <div class=" account-description row">
      <div class="col-12 col-xl-3"></div>
      <div class="col-12 col-xl-3">
        <p class="text-secondary">Пол</p>
        <p>
          {% if user.profileuser.sex == 'M' %}
            Мужской
          {% else %}
            Женский
          {% endif %}
        </p>
        <p class="text-secondary">Дата рождения</p>
        <p>{{ user.profileuser.bday }}</p>
        <p class="text-secondary">Рост</p>
        <p>{{ user.profileuser.height }}</p>
        <p class="text-secondary">Вес</p>
        <p>{{ user.profileuser.weight }}</p>
      </div>
      <div class="col-12 col-xl-6">
        <div class="row m-1">
          <div class="col-12 col-xl-5 m-1 card card-normz">
            <p>Ваш идеальный вес</p>
            <p class="fs-3">{{ idealWeight }} кг</p>
          </div>
          <div class="col-12 col-xl-5 m-1 card card-normz">
            <p>Ваша норма воды</p>
            <p class="fs-3">{{ waterNormal }} л</p>
          </div>
          
        </div>
        <div class="row m-1">
          
          <div class="col-12 col-xl-10 m-1 card card-imt">
            <h4 class="py-2">Ваш индекс массы тела</h4>
            <p class="fs-3">{{ imd }}</p>
            <div>
              <p><strong>Интерпретация показателей на основе рекомендации ВОЗ:</strong></p>
            <ul>
              <li>до 16 – выраженный дефицит массы;</li>
              <li>16 – 17,9 – недостаточная масса тела;</li>
              <li>18 – 24,9 – индекс норма;</li>
              <li>25 – 29,9 – избыточная масса тела;</li>
              <li>30 – 34,9 – ожирение 1 степени;</li>
              <li>35 – 39,9 – ожирение 2 степени;</li>
              <li>свыше 40 – ожирение 3 степени.</li>
            </ul>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
 
  </div>
{% endblock content %}

users/templates/users/register.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-fluid">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Добро пожаловать!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Регистрация</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Уже есть аккаунт? <a class="ml-2" href="#">Вход</a>
            </small>
        </div>
    </div>
{% endblock content %}